### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by pladijs** [wernerkarlheisenberg/plex-vrt_nu_live#2]
I installed the plugin on windows but it doesn't show up under channels. Any suggestions?

**Comment by wernerkarlheisenberg** [comment]
Could you please include the error logs? Did you download the "requests" library as described in the readme?

**Comment by wernerkarlheisenberg** [comment]
Are you running Windows 8 (maybe it also applies to Windows 10 as well). Please have a look at a [similar isssue](https://github.com/wernerkarlheisenberg/plex-stieve/issues/3) is described.

**Comment by pladijs** [comment]
It works now. However the quality is very very low (144p). Any fixes?

**Comment by wernerkarlheisenberg** [comment]
Nice to hear it is working now. Selection of the quality is done automatically.

**Comment by pladijs** [comment]
There must be something up with the quality selection. Stievie works flawlessy in 1080p, VRT nu works in 1080p when watching on my phone but when I try casting to TV or when I watch on my computer, it's in 144p

**Comment by wernerkarlheisenberg** [comment]
I searched the internet an found a [discussion](https://forums.plex.tv/discussion/210417/httplivestreamurl-support-different-bandwidth-settings-for-clients) describing that this is a know issue. It the browser/app that decides on the quality. I checked it myself and it turns out to be true. On chrome the quality is indeed very low, when I use Safari start with a low quality but gradualy increases.
